language: node_js
sudo: required
node_js:
  - 10.15.3
branch: master
cache:
  directories:
    - node_modules
before_install:
  - chmod +x deploy.sh
  - export TZ='Asia/Shanghai'  # 设置时区
script:
  - npm i
  - ./deploy.sh